FROM golang:1.24-alpine AS build

RUN apk --no-cache add curl wget

ENV ENV=production

WORKDIR /go/src/app

COPY . .

RUN go build ./

EXPOSE 80

HEALTHCHECK CMD curl -f http://localhost:80/healthz || exit 1

CMD ["./bang"]
