FROM golang:1.23-alpine

RUN apk --no-cache add curl

ENV ENV=production

WORKDIR /app

COPY go.mod ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o bin/bang ./src

EXPOSE 80

HEALTHCHECK CMD curl -f http://localhost:80/healthz || exit 1

CMD ["./bin/bang"]
